### ISSUE TITLE
Use Pirates

### ISSUE THREAD

**Issue by ariporad** [avajs/require-precompiled#1]
Hi @jamestalmage,

I noticed that your require hook isn't properly respecting the require chain. If I submit a PR, would you consider using `pirates` to do it properly?

Thanks!

**Comment by jamestalmage** [comment]
Continuing down the chain defeats the whole purpose of this module. It does respect the chain if `precompile` returns a falsy value. The idea is to grab from a cache or some other precompilation source instead of continuing down the chain. This requires that you have control over the transorms that come before you if you don't want problems. See my `babel-in-main-thread` branch/PR for AVA. it provides significant speed up.

Obviously, there is danger here if you don't know what you are doing - but I don't think it can be helped in this case.

**Comment by jdalton** [comment]
I was just going to suggest [pirates](https://www.npmjs.com/package/pirates) too.
The chain dead-ending is causing [problems](https://github.com/avajs/ava/issues/1590#issuecomment-353501010) and there's no way to prevent the `precompile` bit.

**Comment by jamestalmage** [comment]
I am certainly open to discussing a solution to the problems `@std/esm` is having, but pirates isn't a viable solution. The whole point of this module is to short-cut the chain. We use it for test sources which we precompile in the main thread to avoid loading Babel in every test thread. This has offered significant performance gains we aren't keen to give up.

I've done some poking around, and`require-precompiled` isn't actually the issue. I'll have a PR for AVA shortly.
